name: check_oks

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run:  composer install
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/grumphp run
